### ISSUE TITLE
Updating Military Bases file

### ISSUE THREAD

**Issue by lindsaypoirier** [Carceral-Ecologies/Carceral-Proximity-Analysis#33]
I discovered a more recent publication of the U.S. Military Installations, Ranges, and Training Areas dataset here: https://www.acq.osd.mil/eie/BSI/BEI_DISDI.html (2019)

I'm working to swap this new dataset out with our current version (https://web.archive.org/web/20150520110927/http://www.acq.osd.mil/ie/bei/disdi.shtml). Unfortunately, some of the geometries are broken in this files, so working to fix them now.

**Comment by shapironick** [comment]
amazing!
